### ISSUE TITLE
[PyFLP 1.x] KeyError when trying `Project.create_zip`

### ISSUE THREAD

**Issue by Yehuda-Edelstein** [demberto/PyFLP#13]
``` File "/Users/almoni/.local/share/virtualenvs/flexporter-8t0uVmD5/lib/python3.9/site-packages/pyflp/project.py", line 118, in create_zip
    il = Path(os.environ["PROGRAMFILES"]) / "Image-Line"
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROGRAMFILES'```

**Comment by demberto** [comment]
Uh yea, that part was specifically coded to run on Windows, Frankly, it never occurred to me that it would definitely fail on Mac or other platforms. Unfortunately there is no direct workaround for this, but you can write your own function which collects all sample paths and creates a zip.

Simply iterate over all the channels in project to get their `sample_path` like this:
```py
from pyflp import Parser

# Uncomment and fill in the path to your FL installation dir below
# I haven't used Mac so don't know where it gets installed.
# FL_INSTALL_DIR: str = ""

paths = []

project = Parser().parse(file_name)
for channel in project.channels:
    if channel.sample_path is not None:
        if channel.sample_path.startswith("%FLStudioFactoryData%"):
            paths.append(channel.sample_path.replace("%FLStudioFactoryData%", FL_INSTALL_DIR, 1)
        else:
            paths.append(channel.sample_path)
```

You will need to write in the code for adding these samples and the FLP to a ZIP yourself. I am sorry I missed such a painfully obvious thing. I am not entirely sure how folders on Mac work, could you please tell me the exact location where FL Studio is installed on Mac (by default)? Can its contents be accessed like if it is a folder (since I read Mac uses `.app` to store apps)?

**Comment by ttaschke** [comment]
@demberto 
> could you please tell me the exact location where FL Studio is installed on Mac (by default)?

Here is an example of a stock sample path in Mac OS:
`/Applications/FL Studio 20.app/Contents/Resources/FL/Data/Patches/Packs/Legacy/Drums/Dance/Kick Basic.wav`

I am on Mac and wanted to try fixing this for Mac users, but it seems that the `create_zip()` functionality is gone with `2.0.0`?

**Comment by demberto** [comment]
> `create_zip()` functionality is gone with `2.0.0`

I plan to create a separate CLI utility for that purpose, since such a platform and software dependant functioniality being in a library doesn't make much sense. Also I plan to make it way more robust than it currently is, much more like FL's actual implementation which looks through current folder, folders added in the sample browser.

I also plan to add my own stuff like fallback paths, conflct resolution etc. Thank you for getting back btw, I will ping you to notify when I create a repo for the CLI.

**Comment by demberto** [comment]
@ttaschke Can you send me over an FLP with a stock sample loaded in it? I want to inspect the sample path stored.

**Comment by ttaschke** [comment]
Here is a FLP saved from the "Basic with Limiter" template 
[stock_sample.flp.zip](https://github.com/demberto/PyFLP/files/9579888/stock_sample.flp.zip)

Example sample path for the first channel:
`/Applications/FL Studio 20.app/Contents/Resources/FL/Data/Patches/Packs/Legacy/Drums/Dance/Kick Basic.wav`

**Comment by demberto** [comment]
Thanks for confirming, FL uses the exact same paths as it would have used on Windows; it uses `%FLStudioFactoryData` for `/Applications/FL Studio 20.app/Contents/Resources/FL` on Mac
